### PR TITLE
add second post to reflections

### PR DESCRIPTION
**Pull request by neuroamanda**

### CODE REVIEW

**Comment by neuroamanda** [comment]
@RaoOfPhysics one more quick look and then merge if ok, thx.

**Comment by RaoOfPhysics** [comment]
Quick comment. Could you perhaps add line breaks after each sentence?

**Comment by neuroamanda** [comment]
that's just for ease of reading, not anything to do with final appearance?
it's kind of a pain...do you insist?

**Comment by RaoOfPhysics** [comment]
Well, we've done it for the main asb posts. Ease of reading and commenting. I would prefer it. But insist? Nope. Your decision! Either way, let me know when I can give it a final read.

**Comment by neuroamanda** [comment]
you're right. will endeavor to do that next time. but for now, please go ahead with final read.

**Comment by RaoOfPhysics** [comment]
LGTM. Good to go.

**Pull request merged**
